[package]
name = "rust_commandlines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap = "0.1.4"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1.5.0"
